#Runa Task notifier config
userinput.login.silently=false
popup.autoclose.timeout=6
server.protocol=http
server.host=$server.host
unread.tasks.notification.timeout=600
userinput.default.password=wf
server.port=$server.web.port
userinput.default.login=Administrator
sounds.enabled=false
check.tasks.timeout=15
