# Enable security check
permission.check.required.EXECUTOR=$securitycheck
permission.check.required.DEFINITION=$securitycheck
permission.check.required.PROCESS=$securitycheck
permission.check.required.REPORT=$securitycheck
permission.check.required.REPORTS=$securitycheck
permission.check.required.RELATIONS=$securitycheck
permission.check.required.RELATION=$securitycheck
permission.check.required.BOTSTATIONS=$securitycheck
permission.check.required.SYSTEM=$securitycheck
permission.check.required.STORAGE_TABLE_COLUMN=true
permission.check.required.DATASOURCES=$securitycheck
permission.check.required.DIGITAL_SIGNATURE=$securitycheck
permission.check.required.DEFINITIONS=$securitycheck
permission.check.required.PROCESSES=$securitycheck
permission.check.required.TASKS=$securitycheck
permission.check.required.EXECUTORS=$securitycheck
permission.check.required.STORAGE=$securitycheck