# Общие настройки для всех сервисов (шаблон) - теперь только для installer.run
x-common: &common
  build:
    context: .. # Чтобы видеть dist/installer.run
  stdin_open: true
  tty: true
  volumes:
    - ../dist:/installer/dist:ro
  env_file:
    - .env
  command: sh -c "/installer/dist/${INSTALLER_FILENAME}"

# Настройки только для GUI сервисов
x-gui: &gui
  <<: *common
  shm_size: '256m'
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /mnt/wslg:/mnt/wslg
    - ../dist:/installer/dist:ro
  environment:
    - DISPLAY=:0
    - WAYLAND_DISPLAY=wayland-0
    - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
    - QT_X11_NO_MITSHM=1
    - GDK_BACKEND=x11
    - NO_AT_BRIDGE=1
  # Сначала инсталлятор, потом mc
  command: sh -c "/installer/dist/${INSTALLER_FILENAME}; xterm -geometry 140x45 -fa 'Monospace' -fs 12 -e mc /opt /usr/share/applications"

services:
  astra17-gui:
    <<: *gui
    build:
      context: ..
      dockerfile: docker/Dockerfile.astra17-gui
    image: astra17-for-izpack-gui

  astra17-console:
    <<: *common
    build:
      context: ..
      dockerfile: docker/Dockerfile.astra17-console
    image: astra17-for-izpack-console

  astra18-gui:
    <<: *gui
    build:
      context: ..
      dockerfile: docker/Dockerfile.astra18-gui
    image: astra18-for-izpack-gui

  astra18-console:
    <<: *common
    build:
      context: ..
      dockerfile: docker/Dockerfile.astra18-console
    image: astra18-for-izpack-console

  altp10-gui:
    <<: *gui
    build:
      context: ..
      dockerfile: docker/Dockerfile.altp10-gui
    image: altp10-for-izpack-gui

  altp10-console:
    <<: *common
    build:
      context: ..
      dockerfile: docker/Dockerfile.altp10-console
    image: altp10-for-izpack-console

  altp11-gui:
    <<: *gui
    build:
      context: ..
      dockerfile: docker/Dockerfile.altp11-gui
    image: altp11-for-izpack-gui

  altp11-console:
    <<: *common
    build:
      context: ..
      dockerfile: docker/Dockerfile.altp11-console
    image: altp11-for-izpack-console

  redos8-gui:
    <<: *gui
    build:
      context: ..
      dockerfile: docker/Dockerfile.redos8-gui
    image: redos8-for-izpack-gui

  redos8-console:
    <<: *common
    build:
      context: ..
      dockerfile: docker/Dockerfile.redos8-console
    image: redos8-for-izpack-console

  macos-gui:
    image: dockurr/macos
    container_name: macos
    environment:
      VERSION: "14"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
      WIDTH: 1280
      HEIGHT: 800
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900/tcp
      - 5900:5900/udp
    volumes:
      - ./macos:/storage
    stop_grace_period: 2m

  win7-gui:
    image: dockurr/windows
    container_name: win7
    environment:
      VERSION: "7"
      REGION: "ru-RU"
      DISK_SIZE: "32G"
      ARGUMENTS: "-vga std -snapshot" 
      RAM_SIZE: "4G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./win7:/storage
      - ../dist:/shared
    stop_grace_period: 2m
    restart: "no"

  altp10-desktop:
    image: qemux/qemu
    container_name: alt-p10-desktop
    environment:
      DISK_SIZE: "20G" 
      RAM_SIZE: "4G"
      CPU_CORES: "4"
      ARGUMENTS: "-snapshot"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      # - ./linux/iso/alt-workstation-10.4-x86_64.iso:/boot.iso
      - ./linux/data:/storage
      - ../dist:/shared
    restart: "no"
    stop_grace_period: 2m
    # root password: 123456
