FROM alt:p10

RUN apt-get update && apt-get install -y \
    libX11 \
    libXext \
    libXrender \
    libXtst \
    libXi \
    libfreetype \
    fontconfig \
    fonts-ttf-dejavu \
    libwebkit2gtk \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /installer
