FROM registry.astralinux.ru/library/astra/ubi17:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    openjdk-11-jre \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /installer
