FROM registry.red-soft.ru/ubi8/ubi:latest

RUN dnf clean all && dnf makecache && dnf install -y \
    libX11 \
    libXext \
    libXrender \
    libXtst \
    libXi \
    freetype \
    fontconfig \
    dejavu-sans-fonts \
    webkit2gtk4.1 \
    xterm mc shared-mime-info \
    && dnf clean all

WORKDIR /installer
