FROM registry.astralinux.ru/library/astra/ubi18:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    libx11-6 \
    libxext6 \
    libxrender1 \
    libxtst6 \
    libxi6 \
    libfreetype6 \
    fontconfig \
    libwebkit2gtk-4.1-0 \
    libgtk2.0-0 \
    xterm mc shared-mime-info \ 
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /installer
